service: backend-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  timeout: 10

functions:
  api:
    handler: dist/lambda.handler
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    target: node18
    platform: node
    concurrency: 10
