service: backend-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  timeout: 29
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:us-east-1:797337948511:table/*

functions:
  api:
    handler: dist/lambda.handler
    timeout: 29
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    target: node18
    platform: node
    concurrency: 10
