export const PRODUCTO_REPOSITORY = 'PRODUCTO_REPOSITORY';
export const COMPRA_REPOSITORY = 'COMPRA_REPOSITORY';
export const CLIENTE_REPOSITORY = 'CLIENTE_REPOSITORY'
export const ENTREGA_REPOSITORY = 'ENTREGA_REPOSITORY'